apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: httpd
  name: httpd
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: httpd
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
