apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: server-john
  name: server-john
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server-john
    spec:
      containers:
      - env:
        - name: NAME
          value: John
        image: server-john
        name: server-john
        resources: {}
      restartPolicy: Always
status: {}
